Fix Compiler error: overloaded functions have similar conversions (#61)
* Fix msvc compiler error C2666 'overloaded functions have similar conversions' when comparing basic_json to std::string_view

* use string getter function instead of converting to string_view

* add braces

* run clang-format